### ISSUE TITLE
Add unit testing for package `astformat`

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#285]
Add unit testing for `internal/stackql/astformat`.

Acceptance Criteria:

- 85% unit test coverage.

**Comment by soysaucewaso** [comment]
I'd like to work on this for my first contribution on this repo.

**Comment by general-kroll-4-life** [comment]
@soysaucewaso fantastic.  There is a [developer quickstart](https://github.com/stackql/stackql/blob/main/docs/developer_guide.md#developer-quickstart) and please reach out if you need assistance.  Best of luck!

**Comment by soysaucewaso** [comment]
Hey sorry for the delay.

Having some trouble with the PostgresSelectExprsFormatter Test.
It has a switch which performs a different action based on the sqlnodes type .
The types are ColName, ColIdent, FuncExpr, GroupConcatExpr, and default. I've seen code where sqlparser.Parse is used to make an SQLNode for tests. How should I test the other Sqlnode types.

I don't think a mock would work since the functions aren't members of the node. I've looked through the stackql/sqlparser repository and found no files with constructors for the different SqlNodes.

Thanks

**Comment by soysaucewaso** [comment]
@general-kroll-4-life view previous comment

**Comment by general-kroll-4-life** [comment]
Hiya @soysaucewaso 

Good question.  Yes pretty much every expression in the grammar is an `SQLNode` so using `Parse` sounds a reasonable approach. 

This code is an inelegant bodge and certainly technical debt.  Naively, if you want coverage then the specified types plus one other should give you that.  If its too much trouble, then maybe just add a comment and move on.

At some point we shall look to purge this sort of tech debt.  Honestly, it may be a while.

Hope this helps.  If not, please ping me and we can discuss.

Cheers
